### ISSUE TITLE
Not working with extension manivest v3 and latest puppeteer version

### ISSUE THREAD

**Issue by vinodreddy-bs** [dequelabs/puppeteer-devtools#63]
Hi,

Is `getDevtoolsPanel()` method still supported for latest puppeteer version? Seems not working with extension manifest v3 and puppeteer version >= 11.

Could you please confirm?

**Comment by scurker** [comment]
It should still work with manifest V3 as we run some of our own tests with a manifest V3 extension. There's been some newer changes to puppeteer that we haven't yet vetted, so my recommendation for now would be to use an older version of puppeteer if possible.

**Comment by vinodreddy-bs** [comment]
Yes, it works with old version. But if I upgrade it to latest, things started breaking. I need to use latest version only as deprecated versions are not allowed at my org.

Can you let me know which part to tweak? I will also look into it

**Comment by scurker** [comment]
I don't have a good handle on it at the moment. Right now, puppeteer just "fails" when trying to find targets of `chrome-extension://` in newer versions.
