### ISSUE TITLE
Update to use newer version of puppeteer

### ISSUE THREAD

**Issue by scurker** [dequelabs/puppeteer-devtools#67]
Currently, `puppeteer-devtools` is pinned to `puppeteer@^9.1.1`, meaning that it's reliant on an unsupported version of puppeteer and respectively an older version of chrome. We need to upgrade but some of the internals that we're using to facilitate e2e testing have changed in newer versions of puppeteer so we need to investigate to see if we can still achieve these methods with a newer version.

Goal: upgrade to the newest version which doesn't require TONS of refactoring - feel free to check in with team to discuss tradeoffs
Time box: 1/2 day (4 hours) to determine how much work we have on our hands

**Comment by thuey** [comment]
The highest I could upgrade with reasonable effort was 14.1.1. I ran into the following issues:
- Puppeteer changed `targetinfo` to a private variable, so our workaround no longer works: https://github.com/dequelabs/puppeteer-devtools/blob/d7011c4332426ca805ba2b93290155de57b1a088/src/index.ts#L43-L45
  - An option to get around this would be to _maybe_ try passing in `_isPageTarget` to puppeteer's `BrowserConnector` class: https://github.com/puppeteer/puppeteer/blob/19111be8d0a7db4d5f1e9c9b9c59fa90bdf5a062/packages/puppeteer-core/src/common/BrowserConnector.ts#L56
  - There is a puppeteer ticket open to add better support for this: https://github.com/puppeteer/puppeteer/issues/9371
- Puppeteer 16.1.0 deprecated execution context, which we rely on here: https://github.com/dequelabs/puppeteer-devtools/blob/d7011c4332426ca805ba2b93290155de57b1a088/src/index.ts#L188-L196
  - An option to get around this would be to stop using puppeteer's execution context, and instead use CDP directly
  - There is a ticket open to better support extension execution contexts: https://github.com/puppeteer/puppeteer/issues/1215

**Comment by thuey** [comment]
I need to update the extension still

**Comment by scurker** [comment]
> I need to update the extension still

Shouldn't we track that from the axe extension?

**Comment by Keerthi-Penukonda** [comment]
Closing this ticket as no testing is required for this change.
